### ISSUE TITLE
Brief README for those following along at home

### ISSUE THREAD

**Issue by thundergolfer** [erikbern/coastlines#1]
Hey Erik, 

This is clearly an early stage project, but as it's public it shows up in my feed. If it isn't a lot of trouble it would be nice to have a `README.md` describing the nature/goals of the project. Would give a bit of context to make following any coming developments here a lot easier. 

Cheers

**Comment by erikbern** [comment]
haha i just put it up here... be a bit patient :)

will prob write a blog post in a few days
